BEGIN TRANSACTION;
ALTER TABLE users RENAME TO users_old;
CREATE TABLE IF NOT EXISTS users (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, companyId INTEGER, email TEXT NOT NULL UNIQUE, first_name TEXT, last_name TEXT DEFAULT 'Doe', createdAt NUMERIC NOT NULL DEFAULT (strftime('%s', 'now')));
DROP TABLE users_old;
COMMIT;